### ISSUE TITLE
Mod causes all player models to be rendered as 1 block tall

### ISSUE THREAD

**Issue by EnderNon** [GoldenShad0w/Inhibitor#1]
Also the player camera is fucked up too

(class menu)
![image](https://github.com/user-attachments/assets/fc44a644-50de-4697-9246-9ed36610deaa)

(f5 mode)
![image](https://github.com/user-attachments/assets/a0bde763-c031-4cb2-8e76-ab6c270338a9)

(cinfras)
![image](https://github.com/user-attachments/assets/3d09b921-2385-41b7-993f-2348534e1f3b)

**Comment by GoldenShad0w** [comment]
yeah it’s kind of a joke feature. I didn’t really apply any kind of quality standards to it. But I can put it on my list of things to look at

**Comment by GoldenShad0w** [comment]
Just disable gnome mode if it bothers you

**Comment by EnderNon** [comment]
i didn't know gnome mode was even on bruh
